name: Node CI
on:
  push:
    branches-ignore:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 13.8.x
    - name: npm install
      run: |
        npm install
    - name: npm lint
      run: |
        npm run lint
    - name: npm build
      run: |
        npm run build
    - name: npm test
      run: |
        npm test
      env:
        CI: true
